name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install build backend
        run: |
          python -m pip install build==1.2.1 twine==5.1.1 packaging

      - name: Build sdist only
        env:
          SAGEATTN_SKIP_CUDA_BUILD: "1"
        run: |
          python -m build --sdist

      - name: Check distribution files
        run: |
          twine check dist/*

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload --skip-existing dist/*
